cc_binary(
    name = "hello_world",
    srcs = ["main.cc"],
    deps = [
        "//deps/GLFW:glfw_static",
        "//deps/glm:glm",
        "//deps/glad:glad",
        "//deps/assimp:assimp",
    ],
)
